# SPDX-License-Identifier: GPL-3.0-only
"""R4 V0 PIN -- are the P2 site-cache svf_patches cubes bit-identical to a
fresh full-tile veg-SVF replay under the CURRENT solver code path?

Runs on the REAL site_500 cache (READ-ONLY) and on the synthetic science site
(tests/test_incremental_worker.py recipe, cache generated by the same
svf_calculator + build_site_cache code).

Evidence: /tmp/r4_proof/v0_site500.json, /tmp/r4_proof/v0_synth.json
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, "/tmp/r4_proof")
from common import (  # noqa: E402
    REPO,
    amplitude_report,
    baseline_scene,
    compare_stack,
    grid_for,
    sweep_absolute,
    sweep_effective,
)

VEG_SCALARS = (
    "svfveg", "svfEveg", "svfSveg", "svfWveg", "svfNveg",
    "svfaveg", "svfEaveg", "svfSaveg", "svfWaveg", "svfNaveg",
)


def v0_site500() -> dict:
    from solweig_gpu.incremental.cache import SiteCache

    t0 = time.time()
    cache = SiteCache.load(REPO / "site-cache" / "site_500")  # read-only
    print(f"loaded site_500 cache in {time.time() - t0:.1f}s "
          f"({cache.rows}x{cache.cols}, patch_count={cache.patch_count})")

    scene, _layer = baseline_scene(cache)
    report = {"site": "site_500", "amplitudes": amplitude_report(cache, scene)}
    amp = report["amplitudes"]
    print("[scene] " + json.dumps(amp, indent=None))

    cached_vegsh = np.asarray(cache.svf_patches["vegshadowmat"])
    cached_vbsh = np.asarray(cache.svf_patches["vbshmat"])

    # --- sweep A: oracle semantics (absolute amaxvalue, full tile) ---
    t0 = time.time()
    abs_vegsh, abs_vbsh = sweep_absolute(cache, scene)
    print(f"[sweep A] absolute-amplitude oracle replay done in {time.time() - t0:.1f}s")

    # --- sweep E: the CURRENT solver code path ---
    t0 = time.time()
    veg_scalars, eff_vegsh, eff_vbsh, svftotal = sweep_effective(cache, scene)
    print(f"[sweep E] current-path full-tile replay done in {time.time() - t0:.1f}s")

    report["A_vs_cache_vegsh"] = compare_stack(abs_vegsh, cached_vegsh, "A-vs-cache vegsh")
    report["A_vs_cache_vbsh"] = compare_stack(abs_vbsh, cached_vbsh, "A-vs-cache vbsh")
    report["E_vs_cache_vegsh"] = compare_stack(eff_vegsh, cached_vegsh, "E-vs-cache vegsh")
    report["E_vs_cache_vbsh"] = compare_stack(eff_vbsh, cached_vbsh, "E-vs-cache vbsh")
    report["E_vs_A_vegsh"] = compare_stack(eff_vegsh, abs_vegsh, "E-vs-A vegsh")
    report["E_vs_A_vbsh"] = compare_stack(eff_vbsh, abs_vbsh, "E-vs-A vbsh")

    # scalar folds (E path) vs cache -- impact quantification only
    scalar_diffs = {}
    for name in VEG_SCALARS:
        cached = np.asarray(cache.window(name, type("W", (), {
            "row_start": 0, "row_stop": cache.rows,
            "col_start": 0, "col_stop": cache.cols})()))
        replay = veg_scalars[name].numpy()
        ndiff = int((cached != replay).sum())
        scalar_diffs[name] = {
            "bitwise_equal": ndiff == 0,
            "mismatch_cells": ndiff,
            "max_abs_diff": float(np.max(np.abs(cached - replay))) if ndiff else 0.0,
        }
    cached_svftotal = np.asarray(cache.window("svftotal", type("W", (), {
        "row_start": 0, "row_stop": cache.rows,
        "col_start": 0, "col_stop": cache.cols})()))
    scalar_diffs["svftotal"] = {
        "bitwise_equal": bool((cached_svftotal == svftotal.numpy()).all()),
        "mismatch_cells": int((cached_svftotal != svftotal.numpy()).sum()),
        "max_abs_diff": float(np.max(np.abs(cached_svftotal - svftotal.numpy()))),
    }
    report["E_scalars_vs_cache"] = scalar_diffs
    eq = all(v["bitwise_equal"] for v in scalar_diffs.values())
    print(f"[scalars] all veg scalars + svftotal bitwise equal: {eq}")

    verdict_A = (report["A_vs_cache_vegsh"]["bitwise_identical"]
                 and report["A_vs_cache_vbsh"]["bitwise_identical"])
    verdict_E = (report["E_vs_cache_vegsh"]["bitwise_identical"]
                 and report["E_vs_cache_vbsh"]["bitwise_identical"])
    print(f"VERDICT site_500: A-vs-cache bit-identical={verdict_A}; "
          f"E(current path)-vs-cache bit-identical={verdict_E}")
    report["verdict_absolute_oracle_vs_cache"] = verdict_A
    report["verdict_current_path_vs_cache"] = verdict_E
    return report


def v0_synth(root: Path) -> dict:
    from solweig_gpu.incremental.cache import SiteCache
    from tests.test_incremental_worker import (
        BASE_TREES,
        DATE_STR,
        SCI_COLS,
        SCI_EPSG,
        SCI_ORIGIN,
        SCI_PIXEL,
        SCI_ROWS,
        _build_cache,
        _compute_baseline_svf,
        _make_prepared_site,
    )

    root.mkdir(parents=True, exist_ok=True)
    grid, site = _make_prepared_site(
        root, rows=SCI_ROWS, cols=SCI_COLS, pixel=SCI_PIXEL,
        origin=SCI_ORIGIN, epsg=SCI_EPSG, base_trees=BASE_TREES,
        met_hours=range(24),
    )
    _compute_baseline_svf(site)  # the real svf_calculator, ABSOLUTE amaxvalue
    cache = _build_cache(
        site, root / "cache_a",
        met_path=site / "metfiles" / f"metfile_0_0_{DATE_STR}.txt",
        site_id="science",
    )
    print(f"built synthetic science site ({SCI_ROWS}x{SCI_COLS}, "
          f"pixel {SCI_PIXEL} m) with oracle SVF cache")

    scene, _layer = baseline_scene(cache)
    report = {"site": "synth_science_192", "amplitudes": amplitude_report(cache, scene)}
    print("[scene] " + json.dumps(report["amplitudes"], indent=None))

    cached_vegsh = np.asarray(cache.svf_patches["vegshadowmat"])
    cached_vbsh = np.asarray(cache.svf_patches["vbshmat"])

    t0 = time.time()
    abs_vegsh, abs_vbsh = sweep_absolute(cache, scene)
    print(f"[sweep A] done in {time.time() - t0:.1f}s")
    t0 = time.time()
    veg_scalars, eff_vegsh, eff_vbsh, _svftotal = sweep_effective(cache, scene)
    print(f"[sweep E] done in {time.time() - t0:.1f}s")

    report["A_vs_cache_vegsh"] = compare_stack(abs_vegsh, cached_vegsh, "synth A-vs-cache vegsh")
    report["A_vs_cache_vbsh"] = compare_stack(abs_vbsh, cached_vbsh, "synth A-vs-cache vbsh")
    report["E_vs_cache_vegsh"] = compare_stack(eff_vegsh, cached_vegsh, "synth E-vs-cache vegsh")
    report["E_vs_cache_vbsh"] = compare_stack(eff_vbsh, cached_vbsh, "synth E-vs-cache vbsh")
    report["E_vs_A_vegsh"] = compare_stack(eff_vegsh, abs_vegsh, "synth E-vs-A vegsh")
    report["E_vs_A_vbsh"] = compare_stack(eff_vbsh, abs_vbsh, "synth E-vs-A vbsh")

    verdict_A = (report["A_vs_cache_vegsh"]["bitwise_identical"]
                 and report["A_vs_cache_vbsh"]["bitwise_identical"])
    verdict_E = (report["E_vs_cache_vegsh"]["bitwise_identical"]
                 and report["E_vs_cache_vbsh"]["bitwise_identical"])
    print(f"VERDICT synth: A-vs-cache bit-identical={verdict_A}; "
          f"E(current path)-vs-cache bit-identical={verdict_E}")
    report["verdict_absolute_oracle_vs_cache"] = verdict_A
    report["verdict_current_path_vs_cache"] = verdict_E
    return report


if __name__ == "__main__":
    which = sys.argv[1] if len(sys.argv) > 1 else "both"
    if which in ("site500", "both"):
        out = v0_site500()
        json.dump(out, open("/tmp/r4_proof/v0_site500.json", "w"), indent=1)
        print("wrote /tmp/r4_proof/v0_site500.json")
    if which in ("synth", "both"):
        out = v0_synth(Path("/tmp/r4_proof/synth_site"))
        json.dump(out, open("/tmp/r4_proof/v0_synth.json", "w"), indent=1)
        print("wrote /tmp/r4_proof/v0_synth.json")
